package com.myteam.serviceusecase;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ambulanceStatus implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("requested")
	private java.lang.Boolean requested;
	@org.kie.api.definition.type.Label(value = "availability")
	private java.lang.Boolean availability;

	@org.kie.api.definition.type.Label(value = "dispatched")
	private java.lang.Boolean dispatched;

	@org.kie.api.definition.type.Label(value = "completed")
	private java.lang.Boolean completed;
	public ambulanceStatus() {
	}

	public java.lang.Boolean getRequested() {
		return this.requested;
	}

	public void setRequested(java.lang.Boolean requested) {
		this.requested = requested;
	}

	public java.lang.Boolean getAvailability() {
		return this.availability;
	}

	public void setAvailability(java.lang.Boolean availability) {
		this.availability = availability;
	}

	public java.lang.Boolean getDispatched() {
		return this.dispatched;
	}

	public void setDispatched(java.lang.Boolean dispatched) {
		this.dispatched = dispatched;
	}

	public java.lang.Boolean getCompleted() {
		return this.completed;
	}

	public void setCompleted(java.lang.Boolean completed) {
		this.completed = completed;
	}

	public ambulanceStatus(java.lang.Boolean requested,
			java.lang.Boolean availability, java.lang.Boolean dispatched,
			java.lang.Boolean completed) {
		this.requested = requested;
		this.availability = availability;
		this.dispatched = dispatched;
		this.completed = completed;
	}

}