package com.myteam.serviceusecase;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CustomerDetailsObject implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label("policyId")
	private java.lang.Integer policyId;
	@org.kie.api.definition.type.Label("ambulance")
	private boolean ambulance;

	@org.kie.api.definition.type.Label("location")
	private java.lang.String location;

	public CustomerDetailsObject() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Integer getPolicyId() {
		return this.policyId;
	}

	public void setPolicyId(java.lang.Integer policyId) {
		this.policyId = policyId;
	}

	public boolean isAmbulance() {
		return this.ambulance;
	}

	public void setAmbulance(boolean ambulance) {
		this.ambulance = ambulance;
	}

	public java.lang.String getLocation() {
		return this.location;
	}

	public void setLocation(java.lang.String location) {
		this.location = location;
	}

	public CustomerDetailsObject(java.lang.String name,
			java.lang.Integer policyId, boolean ambulance,
			java.lang.String location) {
		this.name = name;
		this.policyId = policyId;
		this.ambulance = ambulance;
		this.location = location;
	}

}