package com.myteam.demoproject1;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CaseDetails implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "caseId")
	private java.lang.Integer caseId;
	@org.kie.api.definition.type.Label(value = "Status")
	private java.lang.String status;

	public CaseDetails() {
	}

	public java.lang.Integer getCaseId() {
		return this.caseId;
	}

	public void setCaseId(java.lang.Integer caseId) {
		this.caseId = caseId;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public CaseDetails(java.lang.Integer caseId, java.lang.String status) {
		this.caseId = caseId;
		this.status = status;
	}

}