package com.myteam.demoproject1;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CustDetails implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label(value = "Policy ID")
	private java.lang.Integer policy_id;
	@org.kie.api.definition.type.Label(value = "Location")
	private java.lang.String location;

	public CustDetails() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Integer getPolicy_id() {
		return this.policy_id;
	}

	public void setPolicy_id(java.lang.Integer policy_id) {
		this.policy_id = policy_id;
	}

	public java.lang.String getLocation() {
		return this.location;
	}

	public void setLocation(java.lang.String location) {
		this.location = location;
	}

	public CustDetails(java.lang.String name, java.lang.Integer policy_id,
			java.lang.String location) {
		this.name = name;
		this.policy_id = policy_id;
		this.location = location;
	}

}